package com.cradle.mod.worldgen.structure;

import com.cradle.mod.worldgen.ValleyHeightmap;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;

/**
 * Mount Samara — the central mountain of Sacred Valley.
 * The mountain terrain itself is generated by SacredValleyChunkGenerator;
 * this class adds the Ancestor's Tomb at the summit, a spiral path
 * from base to top, and Yerin's cave carved into the hillside.
 */
public class MountSamaraStructure {
	public static void generate(ServerLevel level) {
		generateAncestorsTomb(level);
		generateSpiralPath(level);
		generateYerinsCave(level);
	}

	/**
	 * Ancestor's Tomb at the summit of Mount Samara (~Y=180).
	 * Small stone brick room with enchanting table altar, 2 chests, glowstone lighting.
	 */
	private static void generateAncestorsTomb(ServerLevel level) {
		int summitY = ValleyHeightmap.getHeight(0, 0);
		// Place tomb on top of the summit
		BlockPos origin = new BlockPos(-4, summitY + 1, -4);

		// Clear area above summit for the tomb
		BuildingPlacer.fill(level, origin, 8, 8, 7, Blocks.AIR);

		// Place the tomb room: 8x8x5
		BuildingPlacer.placeRoom(level, origin, 8, 8, 5,
				Blocks.STONE_BRICKS, Blocks.STONE_BRICKS, Blocks.STONE_BRICKS);

		// Doorway on the south side (positive Z)
		BuildingPlacer.placeDoor(level, new BlockPos(0, summitY + 2, 3));

		// Enchanting table as altar in center
		BuildingPlacer.placeBlock(level, new BlockPos(0, summitY + 2, 0), Blocks.ENCHANTING_TABLE);

		// Two chests flanking the altar
		BuildingPlacer.placeBlock(level, new BlockPos(-2, summitY + 2, 0), Blocks.CHEST);
		BuildingPlacer.placeBlock(level, new BlockPos(2, summitY + 2, 0), Blocks.CHEST);

		// Glowstone lighting in corners
		BuildingPlacer.placeBlock(level, new BlockPos(-3, summitY + 4, -3), Blocks.GLOWSTONE);
		BuildingPlacer.placeBlock(level, new BlockPos(3, summitY + 4, -3), Blocks.GLOWSTONE);
		BuildingPlacer.placeBlock(level, new BlockPos(-3, summitY + 4, 3), Blocks.GLOWSTONE);
		BuildingPlacer.placeBlock(level, new BlockPos(3, summitY + 4, 3), Blocks.GLOWSTONE);
	}

	/**
	 * Spiral gravel path from the base of Mount Samara up to the summit.
	 * Spirals around the mountain at radius ~80, stepping up gradually.
	 */
	private static void generateSpiralPath(ServerLevel level) {
		int baseY = ValleyHeightmap.VALLEY_FLOOR_Y;
		int summitY = ValleyHeightmap.getHeight(0, 0);
		int radius = ValleyHeightmap.MOUNT_SAMARA_RADIUS;
		int totalSteps = 360 * 3; // 3 full rotations to reach the top
		int heightRange = summitY - baseY;

		BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();

		for (int step = 0; step <= totalSteps; step++) {
			double angle = Math.toRadians(step);
			// Shrink radius as we go up to spiral inward
			double progress = (double) step / totalSteps;
			double currentRadius = radius * (1.0 - progress * 0.7); // shrink from 80 to ~24
			int pathY = baseY + (int) (progress * heightRange);

			int pathX = (int) (Math.cos(angle) * currentRadius);
			int pathZ = (int) (Math.sin(angle) * currentRadius);

			// Get terrain height at this position and use max of spiral Y and terrain
			int terrainY = ValleyHeightmap.getHeight(pathX, pathZ);
			int placeY = Math.max(pathY, terrainY);

			// Place a 2-wide path segment
			for (int dx = -1; dx <= 1; dx++) {
				for (int dz = -1; dz <= 1; dz++) {
					pos.set(pathX + dx, placeY, pathZ + dz);
					level.setBlock(pos, Blocks.GRAVEL.defaultBlockState(), 2);
					// Clear 2 blocks above path for walking
					pos.set(pathX + dx, placeY + 1, pathZ + dz);
					level.setBlock(pos, Blocks.AIR.defaultBlockState(), 2);
					pos.set(pathX + dx, placeY + 2, pathZ + dz);
					level.setBlock(pos, Blocks.AIR.defaultBlockState(), 2);
				}
			}
		}
	}

	/**
	 * Yerin's cave — carved into the hillside between the Wei clan and Mount Samara.
	 * Located at approximately (-100, y, -100). 10 blocks deep, 5 wide, 4 tall.
	 * Contains campfire, crafting table, bed. Entrance partially covered with leaves.
	 */
	private static void generateYerinsCave(ServerLevel level) {
		int groundY = ValleyHeightmap.getHeight(-100, -100);
		BlockPos origin = new BlockPos(-102, groundY, -104);

		// Carve out cave interior: 5 wide (X), 10 deep (Z), 4 tall
		BuildingPlacer.fill(level, origin.above(1), 5, 10, 4, Blocks.AIR);

		// Stone floor
		BuildingPlacer.fill(level, origin, 5, 10, 1, Blocks.STONE);

		// Campfire inside
		BuildingPlacer.placeBlock(level, new BlockPos(-100, groundY + 1, -100), Blocks.CAMPFIRE);

		// Crafting table
		BuildingPlacer.placeBlock(level, new BlockPos(-101, groundY + 1, -99), Blocks.CRAFTING_TABLE);

		// Bed (place as a single block — full bed placement requires block states)
		BuildingPlacer.placeBlock(level, new BlockPos(-99, groundY + 1, -98), Blocks.RED_BED);

		// Partial leaf cover at entrance (the Z=-104 face)
		BuildingPlacer.placeBlock(level, new BlockPos(-102, groundY + 3, -104), Blocks.OAK_LEAVES);
		BuildingPlacer.placeBlock(level, new BlockPos(-101, groundY + 3, -104), Blocks.OAK_LEAVES);
		BuildingPlacer.placeBlock(level, new BlockPos(-100, groundY + 4, -104), Blocks.OAK_LEAVES);
		BuildingPlacer.placeBlock(level, new BlockPos(-99, groundY + 3, -104), Blocks.OAK_LEAVES);
		BuildingPlacer.placeBlock(level, new BlockPos(-98, groundY + 3, -104), Blocks.OAK_LEAVES);
		// Lower leaves to partially obscure entrance
		BuildingPlacer.placeBlock(level, new BlockPos(-102, groundY + 2, -104), Blocks.OAK_LEAVES);
		BuildingPlacer.placeBlock(level, new BlockPos(-98, groundY + 2, -104), Blocks.OAK_LEAVES);

		// Torch for light inside
		BuildingPlacer.placeBlock(level, new BlockPos(-100, groundY + 3, -97), Blocks.TORCH);
	}
}
